CREATE TABLE IF NOT EXISTS authors (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books (
  id VARCHAR(255) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  isbn VARCHAR(50) NOT NULL,
  author_id VARCHAR(255) NOT NULL,
  FOREIGN KEY (author_id) REFERENCES authors(id)
);
